import datetime
from datetime import timezone
from langgraph.types import Command
from langgraph.prebuilt import ToolRuntime
from langchain_core.messages import HumanMessage, AIMessage, BaseMessage, AnyMessage
from langchain.messages import ToolMessage, SystemMessage
from langchain.agents.middleware import wrap_tool_call
from langchain_core.tools import tool
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field, ConfigDict, field_validator, ValidationError
from pathlib import Path
from typing import List, Any, Literal, Optional, Annotated
import hashlib
import json
import uuid
import os


class VIZ_INPUT(BaseModel):
    viz_requested : str
    last_validated_sql: str
    table_schema_artifact: str


class MainRouter(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    model_config = ConfigDict(extra = 'ignore')

    intent: Literal['SQL_ONLY', 'SQL_AND_VIZ',  'CLARITY'] = Field(description = """Intent Extracted from current user query.
                                                                  - 'SQL_ONLY': if intent is only to generate sql query from user query.
                                                                  - 'SQL_AND_VIZ': if user intent is to generate sql and visulaize data in graph or plot form.
                                                                  - 'CLARITY': if need more clarification to generate sql.""",)
    last_validated_sql: Optional[str] = Field(
        description="""
        Final validated SQL query generated by SQL_SPECIALIST tool.
        Update ONLY after SQL is successfully validated.
        """
    ),
    table_schema_artifact: str = Field(
        description="""
        Artifact Id of table schema in database.
        """
    ),
    current_invocation_query: str = Field(
        description="""
        Latest user query.
        MUST always contain the current user input.
        """
    ),
    last_invocation_query: Optional[str] = Field(
        description="""
        Previous user query.
        Before updating current_invocation_query, copy its old value here.
        """,
        default = None
    ),
    user_session_summary: Optional[str] = Field(
        description="""
        Compact summary of entire conversation so far.
        Update after every user interaction.
        Keep it short but meaningful.
        """
    ),
    viz_requested: Optional[Literal["bar_chart", "line_chart", "pie_chart", "table", "none"]] = Field(
        description="""
        Type of visualization requested by user.

        Explicit VIX Keywards:
        plot, chart, graph, visulaization, dashboard, trend line, bar chart, line chart, scatter, histogram.

        Choose:
        - bar_chart: comparison across categories
        - line_chart: trends over time
        - pie_chart: proportions
        - table: tabular output requested
        - none: no visualization requested

        If user does not explicitly mention visualization, use 'none'.
        """,
        default = None
    ),
    clarifying_question: Optional[str] = Field(
        description="""
        Ask a question ONLY if user query is ambiguous or missing required info
        to generate SQL.

        Examples:
        - missing table
        - unclear column
        - ambiguous metric

        If query is clear → set to "Cleared".
        """,
        default = None
    ),
    MAX_RETRIES: int = 3,
    MAX_VIZ_RETRIES: int = 3,
    assumptions: Optional[str] = Field(description = "assumption for final generated sql query"),
    final_query_status: Literal['SUCCESS', 'FAIL_NEEDS_CLARIFICATION', 'FAIL_MAX_RETRIES'] = Field(description = 'status of generated sql query'),
    VIZ_STATUS: Literal['SUCCESS','FAIL_MAX_RETRIES'] = Field(description = """Status of visulaization agent"""),
    VIZ_artifact: Optional[str] = Field(description = """Arifact ID of visualization.""", default = None)


class MainState(MainRouter):
    messages: Annotated[List[dict], add_messages]  

class SqlState(MainRouter):
    messages: Annotated[List[dict], add_messages]

class VisualizeState(MainRouter):
    messages: Annotated[List[dict], add_messages]


class LocalArtifactStore:
    def __init__(self, root_dir: str | None = None):
        self.root_dir = Path(
            root_dir or os.getenv("ARTIFACT_ROOT", "./artifact_store")
        )
        self.root_dir.mkdir(parents=True, exist_ok=True)

    def _sha256(self, raw: bytes) -> str:
        return hashlib.sha256(raw).hexdigest()

    def _artifact_dir(self, artifact_id: str) -> Path:
        return self.root_dir / "artifact" / artifact_id

    def save_artifact(
        self,
        data: Any,
        source_tool_name: str | None = None,
        source_tool_call_id: str | None = None,
    ) -> dict:

        artifact_id = str(uuid.uuid4())

        artifact_dir = self._artifact_dir(artifact_id)
        artifact_dir.mkdir(parents=True, exist_ok=True)

        if source_tool_name == "execute_graph":
            fig = pio.from_json(data)

            html = pio.to_html(
                fig,
                full_html=True,
                include_plotlyjs="cdn",
            )

            raw = html.encode("utf-8")
            file_name = "artifact.html"
            mime_type = "text/html"
            artifact_type = "plotly_html"

        else:
            raw = json.dumps(
                data,
                ensure_ascii=False,
                indent=2,
                default=str,
            ).encode("utf-8")

            file_name = "artifact.json"
            mime_type = "application/json"
            artifact_type = "json"

        file_path = artifact_dir / file_name
        print("artifact_dir:", artifact_dir, type(artifact_dir))
        print("file_path:", artifact_dir / file_name)
        file_path.write_bytes(raw)

        manifest = {
            "schema_version": "1.0",
            "artifact_id": artifact_id,
            "artifact_type": artifact_type,
            "file_name": file_name,
            "mime_type": mime_type,
            "storage_backend": "local",
            "size_bytes": len(raw),
            "sha256": self._sha256(raw),
            "source_tool_name": source_tool_name,
            "source_tool_call_id": source_tool_call_id,
            "uri": f"file://{file_path.resolve().as_posix()}",
            "object_key": f"artifact/{artifact_id}/{file_name}",
        }

        manifest_path = artifact_dir / "manifest.json"

        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        return manifest
    
    def get_manifest(self, artifact_id: str) -> dict:
        manifest_path = self._artifact_dir(artifact_id)/ 'manifest.json'

        if not manifest_path.exists():
            raise FileNotFoundError('Artifact not found')
        
        return json.loads(manifest_path.read_text(encoding = 'utf-8'))
    
    def load_artifact(self, artifact_id: str):
        manifest = self.get_manifest(artifact_id)

        file_path = self._artifact_dir(artifact_id)/ manifest['file_name']

        raw = file_path.read_bytes()

        if self._sha256(raw) != manifest['sha256']:
            raise ValueError('Check mismatch')
        
        if manifest['artifact_type'] == 'json':
            return json.loads(raw.decode('utf-8')), manifest
        
        if manifest['artifact_type'] == 'plotly_html':
            return raw.decode('utf-8'), manifest
        
        raise

@tool
def get_artifact(artifact_id: str):
    """
    Load artifact by artifact_id.
    
    """
    artifact_store = LocalArtifactStore()
    data, manifest = artifact_store.load_artifact(artifact_id)

    if manifest['artifact_type'] == 'json':
        print('final_return artifacy')
        return json.dumps({
            'artifact_id': artifact_id,
            'artifact_type': 'json',
            'data': data
        },
        ensure_ascii = False,
        default = str)

    if manifest['artifact_type'] == 'plotly_html':
        return json.dumps({
            'artifact_id': artifact_id,
            'artifact_type': 'plotly_html',
            'mime_type': manifest['mime_type'],
            'uri': manifest['uri']},
        ensure_ascii = False,
        )

@wrap_tool_call
async def store_artifact(request, handler):

    result = await handler(request)
    if (
        request.tool_call
        and request.tool_call["name"].lower() == "get_sql_table_schema"
    ):
        artifact_store = LocalArtifactStore()
        payload = json.loads(result.content[0]["text"])
        
        if payload['status'].lower() == 'success':

            manifest = artifact_store.save_artifact(
                data = payload["data"],
                source_tool_name = request.tool_call["name"],
                source_tool_call_id = request.tool_call["id"],
            )

            artifact_ref = {
                "artifact_id": manifest["artifact_id"],
                "artifact_type": manifest["artifact_type"],
                "mime_type": manifest["mime_type"],
                "uri": manifest["uri"],
            }

            payload["data"] = artifact_ref
            result.content[0]["text"] = json.dumps(payload)
            result.artifact = artifact_ref

        return result

    
    if (
        request.tool_call
        and request.tool_call['name'].lower() == 'execute_graph'
    ):
        
        artifact_store = LocalArtifactStore()
        payload = json.loads(result.content[0].get('text'))

        if payload['status'].lower() == 'success':
            manifest = artifact_store.save_artifact(
                data = json.dumps(payload['data']), 
                source_tool_name = request.tool_call["name"], 
                source_tool_call_id = request.tool_call["id"]
            )

            artifact_ref = {
                'artifact_id': manifest['artifact_id'],
                'artifact_type': manifest['artifact_type'],
                'mime_type': manifest['mime_type'],
                'uri': manifest['uri']
            }
            
            payload['data'] = artifact_ref
            result.content[0]['text'] = json.dumps(payload)
            result.artifact = artifact_ref
        
        return result

    return result

@tool(args_schema=MainRouter)
def update_state(runtime: ToolRuntime, **kwargs):
    """Update the application state with specific allowed keys."""

    patch = MainRouter(**kwargs)
    return Command(update = {**patch.model_dump(exclude_unset = True, exclude_none = True),
                             'messages': [ToolMessage(content = 'State Updated Successfully', tool_call_id = runtime.tool_call_id,)]})